{
 "title": "Jamf Pro Test Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Device Last Enrollment Date",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  last_enrolled_date_epoch AS \"time\",\n  OS AS metric,\n  Device_id AS \"Device_id\"\nFROM devices\nORDER BY last_enrolled_date_epoch"
    }
   ]
  },
  {
   "title": "Model identifier",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Device_id AS \"time\",\n  model_identifier AS metric,\n  Device_id AS \"Device_id\"\nFROM devices\nORDER BY Device_id"
    }
   ]
  },
  {
   "title": "Device by department and OS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Device_id AS \"time\",\n  department_name AS metric,\n  Device_id AS \"Device_id\"\nFROM devices\nORDER BY Device_id"
    },
    {
     "rawSql": "SELECT\n  Device_id AS \"time\",\n  OS AS metric,\n  Device_id AS \"Device_id\"\nFROM devices\nORDER BY Device_id"
    }
   ]
  },
  {
   "title": "Device Report Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  last_enrolled_date_epoch AS \"time\",\n  OS AS metric,\n  last_report_id AS \"last_report_id\"\nFROM devices\nORDER BY last_enrolled_date_epoch"
    }
   ]
  }
 ]
}